# -*- coding: utf-8 -*-
"""PythonSession.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VAVrwjkW0ABT-hZuyahRCqqhymjapswX
"""

a = 10
b = 3

print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a % b)
print(a ** b)

a = 10
b = 20

print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)

age = 21
has_id = True

print(age >= 18 and has_id)
print(age >= 18 or has_id)
print(not has_id)

a = 5
b = 3

print(a & b)
print(a | b)
print(a ^ b)
print(~a)
print(a << 1)
print(a >> 1)

x = 10

x += 5
print(x)

x -= 2
print(x)

x *= 3
print(x)

x /= 2
print(x)

x //= 2
print(x)

x %= 3
print(x)

x **= 2
print(x)

a = [1, 2, 3]
b = a
c = [1, 2, 3]

print(a is b)
print(a is c)

print(a is not c)

"""CONDITIONAL STATEMENT

IF STATEMENT
"""

age = int(input("Enter your age: "))

if age >= 18:
    print("You are eligible to vote")

"""IF ELSE"""

age = int(input("Enter your age: "))

if age >= 18:
    print("Eligible to vote")
else:
    print("Not eligible to vote")

"""If-Elif-Else"""

marks = int(input("Enter your marks: "))

if marks >= 90:
    print("Grade A")
elif marks >= 75:
    print("Grade B")
elif marks >= 60:
    print("Grade C")
elif marks >= 40:
    print("Grade D")
else:
    print("Fail")

"""**Nested If-Else**"""

age = int(input("Enter your age: "))
has_id = input("Do you have ID? ")

if age >= 18:
    if has_id == "yes":
        print("Entry allowed")
    else:
        print("ID required")
else:
    print("Entry not allowed")

"""Mini Project — Grade Calculator"""

marks = float(input("Enter your marks: "))

if marks >= 90:
    grade = "A"
elif marks >= 75:
    grade = "B"
elif marks >= 60:
    grade = "C"
elif marks >= 40:
    grade = "D"
else:
    grade = "F"

print("Your Grade:", grade)

"""LOOP"""

print(1)
print(2)
print(3)
print(4)
print(5)
print(6)
print(7)
print(8)
print(9)
print(10)

for i in range(1, 11):
    print(i)

i = 1

while i <= 5:
    print(i)
    i += 1

"""Break"""

for i in range(1, 11):

    if i == 6:
        break

    print(i)

"""Continue"""

for i in range(1, 11):

    if i == 5:
        continue

    print(i)

"""Perform the Sum operation of numbers  n times"""

n = int(input("Enter N: "))

total = 0

for i in range(1, n + 1):
    total += i

print("Sum:", total)

"""Even Number"""

n = int(input("Enter N: "))

for i in range(1, n + 1):

    if i % 2 == 0:
        print(i)

"""Pattern Challenges"""

n = int(input("Enter rows: "))

for i in range(1, n + 1):
    print("*" * i)

"""**Functions**"""

def greet():
    print("Hello Python!")

greet()

def add(a, b):
    print(a + b)

add(10, 20)

def add(a, b):
    return a + b

result = add(10, 20)

print(result)